name: Test Communication Formulaire
on:
  repository_dispatch:
    # On définit un type d'événement personnalisé
    types: [test_webhook]

jobs:
  display_info:
    runs-on: ubuntu-latest
    steps:
      - name: Afficher les données reçues
        run: |
          echo "Le nom du photographe reçu est : ${{ github.event.client_payload.photographe }}"
          echo "Message de debug : Connexion établie avec succès !"